In [9]:
import numpy as np
data = np.array([[1], [2], [3]])

In [10]:
data.ndim

2

In [11]:
data

array([[1],
       [2],
       [3]])

In [12]:
arr = np.array([[[[[[[[[[[[1,2,3],[4,5,6]]]]]]]]]]]])

In [13]:
arr

array([[[[[[[[[[[[1, 2, 3],
                 [4, 5, 6]]]]]]]]]]]])

In [14]:
arr.ndim

12

In [15]:
arr.shape

(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3)

In [16]:
np.squeeze(arr)

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
one_array = np.ones((1,1,1,1,1,1,2,3,4))
one_array

array([[[[[[[[[1., 1., 1., 1.],
              [1., 1., 1., 1.],
              [1., 1., 1., 1.]],

             [[1., 1., 1., 1.],
              [1., 1., 1., 1.],
              [1., 1., 1., 1.]]]]]]]]])

In [18]:
one_array.ndim

9

In [19]:
np.squeeze(one_array)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [20]:
a.ndim

NameError: name 'a' is not defined

In [ ]:
data = np.array([[1],[2],[3]])

In [ ]:
#repeat
data

In [ ]:
np.repeat(data, 4)

In [ ]:
a = np.array([[1, 2], [3, 4]])

In [ ]:
a

In [ ]:
np.repeat(a, 2)

In [ ]:
a

In [ ]:
np.repeat(a, 2, axis = 0)

In [ ]:
a

In [ ]:
np.repeat(a, 2, axis = 1)

In [ ]:
data

In [ ]:
np.roll(data, -1)

In [ ]:
np.roll(data, -2)

In [ ]:
np.roll(data, 11)

In [21]:
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [22]:
#binary operation on array

In [23]:
arr1 = np.random.randint(1, 10, (3, 4))
arr2 = np.random.randint(1, 10, (3, 4))

In [24]:
arr1

array([[7, 9, 3, 6],
       [7, 2, 4, 1],
       [4, 9, 8, 7]])

In [25]:
arr2

array([[7, 4, 9, 8],
       [9, 2, 5, 9],
       [8, 2, 6, 6]])

In [26]:
arr1+arr2

array([[14, 13, 12, 14],
       [16,  4,  9, 10],
       [12, 11, 14, 13]])

In [27]:
arr1*arr2

array([[49, 36, 27, 48],
       [63,  4, 20,  9],
       [32, 18, 48, 42]])

In [28]:
arr1 / arr2

array([[1.        , 2.25      , 0.33333333, 0.75      ],
       [0.77777778, 1.        , 0.8       , 0.11111111],
       [0.5       , 4.5       , 1.33333333, 1.16666667]])

In [29]:
arr1 - arr2

array([[ 0,  5, -6, -2],
       [-2,  0, -1, -8],
       [-4,  7,  2,  1]])

In [30]:
arr1

array([[7, 9, 3, 6],
       [7, 2, 4, 1],
       [4, 9, 8, 7]])

In [31]:
arr2

array([[7, 4, 9, 8],
       [9, 2, 5, 9],
       [8, 2, 6, 6]])

In [32]:
arr1 ** arr2

array([[  823543,     6561,    19683,  1679616],
       [40353607,        4,     1024,        1],
       [   65536,       81,   262144,   117649]], dtype=int32)

In [33]:
arr1

array([[7, 9, 3, 6],
       [7, 2, 4, 1],
       [4, 9, 8, 7]])

In [34]:
arr2

array([[7, 4, 9, 8],
       [9, 2, 5, 9],
       [8, 2, 6, 6]])

In [35]:
arr1 > arr2

array([[False,  True, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [36]:
arr1

array([[7, 9, 3, 6],
       [7, 2, 4, 1],
       [4, 9, 8, 7]])

In [37]:
~arr1

array([[ -8, -10,  -4,  -7],
       [ -8,  -3,  -5,  -2],
       [ -5, -10,  -9,  -8]], dtype=int32)

In [38]:
arr1

array([[7, 9, 3, 6],
       [7, 2, 4, 1],
       [4, 9, 8, 7]])

In [39]:
#Numpy string function

In [40]:
arr = np.array(["Soft", "Crayons"])

In [41]:
arr

array(['Soft', 'Crayons'], dtype='<U7')

In [42]:
np.char.upper(arr)

array(['SOFT', 'CRAYONS'], dtype='<U7')

In [43]:
np.char.upper(np.array(["Ajay"]))

array(['AJAY'], dtype='<U4')

In [44]:
np.char.capitalize(arr)

array(['Soft', 'Crayons'], dtype='<U7')

In [203]:
np.char.title(arr)

array(['Soft', 'Crayons'], dtype='<U7')

In [205]:
a = 'asdf'

In [206]:
#Mathematical function


arr1

array([[2, 9, 7, 1],
       [1, 8, 7, 2],
       [2, 9, 7, 7]])

In [208]:
np.sin(arr1)

array([[0.90929743, 0.41211849, 0.6569866 , 0.84147098],
       [0.84147098, 0.98935825, 0.6569866 , 0.90929743],
       [0.90929743, 0.41211849, 0.6569866 , 0.6569866 ]])

In [209]:
np.cos(arr1)

array([[-0.41614684, -0.91113026,  0.75390225,  0.54030231],
       [ 0.54030231, -0.14550003,  0.75390225, -0.41614684],
       [-0.41614684, -0.91113026,  0.75390225,  0.75390225]])

In [210]:
np.tan(arr1)

array([[-2.18503986, -0.45231566,  0.87144798,  1.55740772],
       [ 1.55740772, -6.79971146,  0.87144798, -2.18503986],
       [-2.18503986, -0.45231566,  0.87144798,  0.87144798]])

In [211]:
np.log10(arr1)

array([[0.30103   , 0.95424251, 0.84509804, 0.        ],
       [0.        , 0.90308999, 0.84509804, 0.30103   ],
       [0.30103   , 0.95424251, 0.84509804, 0.84509804]])

In [212]:
np.exp(arr1)

array([[7.38905610e+00, 8.10308393e+03, 1.09663316e+03, 2.71828183e+00],
       [2.71828183e+00, 2.98095799e+03, 1.09663316e+03, 7.38905610e+00],
       [7.38905610e+00, 8.10308393e+03, 1.09663316e+03, 1.09663316e+03]])

In [213]:
arr1

array([[2, 9, 7, 1],
       [1, 8, 7, 2],
       [2, 9, 7, 7]])

In [214]:
np.power(arr1, 3)

array([[  8, 729, 343,   1],
       [  1, 512, 343,   8],
       [  8, 729, 343, 343]], dtype=int32)

In [215]:
np.mean(arr1)

5.166666666666667

In [216]:
np.max(arr1)

9

In [220]:
np.std(arr1)

3.1046560016995266

In [221]:
np.var(arr1)

9.638888888888891

In [219]:
np.max(arr1)

9

In [222]:
arr1 - arr2

array([[ 0,  7,  1, -8],
       [-3,  1, -1, -5],
       [-4,  0,  5,  5]])

In [223]:
np.subtract(arr1, arr2)

array([[ 0,  7,  1, -8],
       [-3,  1, -1, -5],
       [-4,  0,  5,  5]])

In [224]:
arr1 * arr2

array([[ 4, 18, 42,  9],
       [ 4, 56, 56, 14],
       [12, 81, 14, 14]])

In [225]:
np.multiply(arr1, arr2)

array([[ 4, 18, 42,  9],
       [ 4, 56, 56, 14],
       [12, 81, 14, 14]])

In [234]:
np.mod(arr1, arr2) #return element wise remainder

array([[0, 1, 1, 1],
       [1, 1, 7, 2],
       [2, 0, 1, 1]], dtype=int32)

In [235]:
arr1

array([[2, 9, 7, 1],
       [1, 8, 7, 2],
       [2, 9, 7, 7]])

In [236]:
arr2

array([[2, 2, 6, 9],
       [4, 7, 8, 7],
       [6, 9, 2, 2]])

In [237]:
np.power(arr1, arr2)

array([[        4,        81,    117649,         1],
       [        1,   2097152,   5764801,       128],
       [       64, 387420489,        49,        49]], dtype=int32)

In [238]:
np.sqrt(arr1)

array([[1.41421356, 3.        , 2.64575131, 1.        ],
       [1.        , 2.82842712, 2.64575131, 1.41421356],
       [1.41421356, 3.        , 2.64575131, 2.64575131]])

In [239]:
#sort search

In [240]:
arr = np.array([5, 6, 1, 2])

In [241]:
arr

array([5, 6, 1, 2])

In [242]:
np.sort(arr)

array([1, 2, 5, 6])

In [243]:
arr = np.array([5, 6,100, 200, 1, 2, 8, 9])

In [244]:
# a = np.sort(arr)

In [245]:
arr

array([  5,   6, 100, 200,   1,   2,   8,   9])

In [246]:
np.sort(arr)

array([  1,   2,   5,   6,   8,   9, 100, 200])

In [247]:
arr1 = np.array([0, 1, 2, 3, 0, 4])
np.count_nonzero(arr1)

4

In [248]:
arr1 > 0

array([False,  True,  True,  True, False,  True])

In [249]:
arr1

array([0, 1, 2, 3, 0, 4])

In [250]:
np.where(arr1 > 0)

(array([1, 2, 3, 5], dtype=int64),)

In [251]:
np.extract(arr1 > 0, arr1)

array([1, 2, 3, 4])

In [252]:
#matrix >> 2d array

In [253]:
import numpy.matlib as nm

In [254]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [255]:
nm.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [256]:
#Numpy linear algebra

In [257]:
arr1

array([0, 1, 2, 3, 0, 4])

In [258]:
arr1 = np.array([[2, 3], [4, 5]])
arr2 = np.array([[1, 3], [4, 5]])

In [259]:
arr1 @ arr2

array([[14, 21],
       [24, 37]])

In [260]:
a  = np.array([[7, 5.3, -3], [3, -5, 2], [5, 3, -7]])

In [261]:
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [262]:
b = np.array([16, -8, 0])

In [263]:
b

array([16, -8,  0])

In [264]:
arr1

array([[2, 3],
       [4, 5]])

In [265]:
5*2 - 3*4

-2