In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,6]

In [3]:
l

[1, 2, 3, 4, 5, 6]

In [4]:
x = np.array(l)

In [7]:
x

array([1, 2, 3, 4, 5, 6])

In [8]:
x.ndim

1

In [9]:
type(x)

numpy.ndarray

In [10]:
l = [1, 2, 3, 4, 5, "Rishi"]
l

[1, 2, 3, 4, 5, 'Rishi']

In [12]:
np.array(l)

array(['1', '2', '3', '4', '5', 'Rishi'], dtype='<U11')

In [15]:
l = [[1, 2, 3], [4, 5, 6]]
l

[[1, 2, 3], [4, 5, 6]]

In [18]:
np.ndim(l)

2

In [19]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
np.matrix([[1, 2, 3], [4, 5, 6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [60]:
np.matrix([[[1, 2], [5, 6], [7, 8]]])

ValueError: matrix must be 2-dimensional

In [61]:
np.array([[[1, 2], [5, 6], [7, 8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [62]:
t = ((1, 2, 3), [4, 5, 6])
x = np.array(t)

In [63]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
x.shape

(2, 3)

In [65]:
x.size

6

In [66]:
np.fromfunction(lambda i, j : i == j, ( 3 , 3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [67]:
range(10)

range(0, 10)

In [68]:
list(range(1,12,3))

[1, 4, 7, 10]

In [69]:
range(0.2,5.5)

TypeError: 'float' object cannot be interpreted as an integer

In [70]:
np.arange(0.5,9.5,0.5)

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. ])

In [71]:
np.arange(0.2,5.5,0.1)

array([0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3, 1.4,
       1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7,
       2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. ,
       4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3,
       5.4])

In [72]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [53]:
np.logspace(1,5,10,base = 2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [73]:
arr1 = np.zeros((5,5,2))
arr1

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [74]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [75]:
x = np.ones((5,3))

In [76]:
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [77]:
x * 5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [78]:
x + 2

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [79]:
x = np.array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 1, 1, 1, 1, 1 ]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

C:\Users\gaura\AppData\Local\Temp\ipykernel_6832\2372955543.py:1: VisibleDeprecationWarning: Creating an ndarray from nested sequences exceeding the maximum number of dimensions of 32 is deprecated. If you mean to do this, you must specify 'dtype=object' when creating the ndarray.
  x = np.array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 1, 1, 1, 1, 1 ]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])


In [31]:
x

array([[[[[[[[[[[[[[[[1, 1, 1, 1, 1, 1]]]]]]]]]]]]]]]])

In [32]:
x.ndim

16

In [ ]:
np.