In [1]:
#pip install numpy

In [33]:
import numpy as np #2005 by Travis Oliphant

In [34]:
#Why numpy
#-mathematical function
#Faster 

In [35]:
l = [1, 2, 3, 4, 5]

In [36]:
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [37]:
type(arr)

numpy.ndarray

In [38]:
arr.shape

(5,)

In [39]:
arr.ndim

1

In [40]:
l = [1, 2, 3, 4, 5, "Ajay","Suraj"]
arr1 = np.array(l)
arr1

array(['1', '2', '3', '4', '5', 'Ajay', 'Suraj'], dtype='<U11')

In [41]:
arr1.ndim

1

In [42]:
arr1.shape

(7,)

In [43]:
l = [[1, 2, 3], [4, 5, 6],[8,9,3]]
l

[[1, 2, 3], [4, 5, 6], [8, 9, 3]]

In [44]:
l

[[1, 2, 3], [4, 5, 6], [8, 9, 3]]

In [45]:
arr1 = np.array(l)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 3]])

In [46]:
arr1.ndim

2

In [47]:
arr1.shape

(3, 3)

In [48]:
l = [1, 2, 3, 4]

In [49]:
mat = np.matrix(l) #matris will be by default 2d

In [50]:
mat

matrix([[1, 2, 3, 4]])

In [51]:
type(mat)

numpy.matrix

In [52]:
np.matrix([[1, 2], [5, 6], [7, 8]])

matrix([[1, 2],
        [5, 6],
        [7, 8]])

In [53]:
np.matrix([[[1, 2], [5, 6], [7, 8]]])   # matrix cannot convert more then 2dimension into 2dimension its shows error

ValueError: matrix must be 2-dimensional

In [54]:
np.array([[[1, 2], [5, 6], [7, 8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [55]:
np.asanyarray([[[1, 2], [5, 6], [7, 8]]]) #Convert the input to an ndarray, but pass ndarray subclasses through.

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [56]:
mat

matrix([[1, 2, 3, 4]])

In [57]:
np.array(mat)

array([[1, 2, 3, 4]])

In [58]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [59]:
np.array(mat)

array([[1, 2, 3, 4]])

In [60]:
np.asarray([[[1, 2], [5, 6], [7, 8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [61]:
np.array([[[1, 2], [5, 6], [7, 8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [62]:
t = ((1, 2, 3), [4, 5, 6])
type(t)

tuple

In [63]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

### Shallow Copy

In [75]:
arr

array([ 1,  2, 10,  4,  5])

In [76]:
n = arr

In [77]:
n

array([ 1,  2, 10,  4,  5])

In [78]:
n[2] = 100

In [79]:
n

array([  1,   2, 100,   4,   5])

In [80]:
arr

array([  1,   2, 100,   4,   5])

In [85]:
a = [4]
b = [4]

In [86]:
a == b

True

In [87]:
a is b

False

### Deep Copy

In [96]:
a = arr

In [97]:
b = a.copy()          #deep copy

In [98]:
b

array([  1,   2, 100,   4,   5])

In [99]:
a

array([  1,   2, 100,   4,   5])

In [100]:
b is a

False

In [101]:
a[3] = 100

In [102]:
a

array([  1,   2, 100, 100,   5])

In [103]:
b

array([  1,   2, 100,   4,   5])

In [104]:
#to create array >> .array, .asasrray, .asanyarray, deep copy, shallow copy

In [105]:
#There are multiple ways to generating arrays

In [108]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [110]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [111]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
range(10)

range(0, 10)

In [113]:
np.fromiter(range(10),"float")

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [114]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
# arr.shape

In [116]:
arr.dtype

dtype('int32')

In [117]:
arr.shape

(5,)

In [121]:
np.linspace(1, 5, 10,endpoint=False) # I want 20 values between 1 to 5

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6])

In [123]:
np.logspace(start = 1,stop = 5, num = 10, base = 2)   # make log with log base 2 - log2()

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [124]:
np.logspace(1, 5, 10, base = 10) 

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [128]:
np.log(20)

2.995732273553991

In [130]:
arr1 = np.zeros((5,4))
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [136]:
arr2 = np.zeros((3, 3, 2))
arr2

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [137]:
arr2

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [138]:
arr2.ndim

3

In [144]:
arr = np.ones((2,4,3,4),dtype = "int")
arr

array([[[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]],


       [[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]]])

In [152]:
x = np.array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[5]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])
x

C:\Users\gaura\AppData\Local\Temp\ipykernel_5524\425048448.py:1: VisibleDeprecationWarning: Creating an ndarray from nested sequences exceeding the maximum number of dimensions of 32 is deprecated. If you mean to do this, you must specify 'dtype=object' when creating the ndarray.
  x = np.array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[5]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])


array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[list([[[[[[[[[[[[[[[[[[[5]]]]]]]]]]]]]]]]]]])]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]],
      dtype=object)

In [151]:
np.ndim(x)

32