In [2]:
import numpy as np

In [3]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.zeros((7,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
arr = np.ones((3, 4))

In [6]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [8]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [11]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [12]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### We do all this things in numpy library without importing random library

In [13]:
import random

In [71]:
random.randint(1,6)

5

In [60]:
random.randint(2,10)

2

In [74]:
np.random.randint(50,100,10)

array([79, 82, 79, 94, 70, 85, 86, 97, 51, 50])

In [75]:
np.random.randint(50,100,size=200)

array([60, 74, 81, 51, 77, 71, 83, 53, 79, 87, 70, 62, 67, 72, 68, 90, 94,
       67, 84, 91, 57, 62, 80, 56, 97, 94, 94, 72, 50, 83, 74, 63, 70, 60,
       52, 79, 86, 90, 99, 79, 94, 55, 53, 80, 64, 93, 80, 78, 56, 84, 76,
       72, 56, 65, 89, 80, 69, 57, 63, 86, 73, 86, 76, 73, 51, 91, 68, 93,
       68, 51, 88, 67, 63, 68, 51, 57, 90, 74, 56, 65, 60, 57, 51, 85, 95,
       62, 73, 66, 65, 91, 51, 90, 95, 92, 91, 98, 99, 61, 66, 78, 69, 92,
       83, 95, 60, 71, 94, 84, 64, 63, 69, 83, 65, 67, 67, 54, 68, 84, 86,
       61, 83, 76, 87, 68, 70, 84, 75, 65, 70, 50, 58, 94, 78, 61, 57, 68,
       65, 83, 82, 65, 62, 74, 61, 69, 84, 96, 95, 63, 92, 76, 78, 60, 93,
       67, 93, 91, 90, 93, 50, 74, 50, 56, 59, 81, 95, 73, 60, 85, 89, 93,
       56, 69, 93, 82, 62, 78, 63, 63, 83, 55, 64, 70, 99, 91, 77, 61, 76,
       50, 78, 70, 98, 99, 81, 67, 62, 52, 80, 52, 57, 91])

In [145]:
np.random.random_sample((9,5))

array([[0.73899108, 0.83721447, 0.13934211, 0.07298784, 0.90123664],
       [0.06518791, 0.77896401, 0.4692949 , 0.343006  , 0.47211467],
       [0.13219418, 0.48403784, 0.141211  , 0.8625505 , 0.84470878],
       [0.97845981, 0.20063802, 0.60608956, 0.07507009, 0.31272177],
       [0.90542806, 0.35377583, 0.11000695, 0.99617252, 0.26427151],
       [0.99459428, 0.06030323, 0.51141148, 0.24072589, 0.29070375],
       [0.75297449, 0.81590371, 0.17939421, 0.71315559, 0.2224888 ],
       [0.69334335, 0.18064262, 0.98915288, 0.76958372, 0.09056002],
       [0.54764405, 0.78212143, 0.44153132, 0.86672165, 0.32628273]])

In [167]:
np.random.random_sample()

0.6835252700411304

In [169]:
np.random.random_sample(10)

array([0.21630386, 0.95117658, 0.37394029, 0.78906109, 0.61489285,
       0.8489829 , 0.1892272 , 0.08298534, 0.55160119, 0.94151942])

In [170]:
np.random.rand(10,2)

array([[0.75110347, 0.91723842],
       [0.86663279, 0.89447651],
       [0.71692199, 0.94284372],
       [0.05638451, 0.51804888],
       [0.19061477, 0.50421782],
       [0.80875094, 0.28820999],
       [0.4410647 , 0.94304996],
       [0.05445353, 0.92984015],
       [0.32500437, 0.31017969],
       [0.63162938, 0.89626907]])

In [171]:
np.random.rand(2, 3)

array([[0.19670188, 0.18094174, 0.21043861],
       [0.41169785, 0.56011939, 0.66172039]])

In [172]:
np.random.randn(2, 3)

array([[ 0.37009593,  0.95900368, -0.3968116 ],
       [-0.59653143, -1.43489205,  0.42585197]])

In [173]:
np.random.random_sample()

0.7322529547106705

In [174]:
np.random.randint(1,7)

4

In [175]:
np.random.randint(1,7,(4,6))

array([[3, 5, 4, 6, 6, 1],
       [3, 2, 6, 6, 4, 2],
       [5, 1, 1, 4, 3, 5],
       [1, 1, 6, 5, 4, 3]])

In [178]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [179]:
arr.size

12

In [180]:
arr.shape

(3, 4)

In [187]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [188]:
arr.reshape(6,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [189]:
arr.reshape(2,6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [190]:
arr.reshape(12,1)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [198]:
arr.reshape(-1,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [199]:
arr.reshape(1,12) #array size can not change, multiples of array size

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [200]:
arr.reshape(3, -541)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [201]:
arr.reshape(15,-1)

ValueError: cannot reshape array of size 12 into shape (15,newaxis)

In [202]:
arr.reshape(6, -1)  
# when we know how many rows wants but not know about columns so we use -1 it automatically decides the no. of columns

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [203]:
arr.reshape(1, 2, 2, 3)

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])

In [204]:
arr.reshape(1,1,1,1,4, 3, 1)

array([[[[[[[1.],
            [1.],
            [1.]],

           [[1.],
            [1.],
            [1.]],

           [[1.],
            [1.],
            [1.]],

           [[1.],
            [1.],
            [1.]]]]]]])

In [206]:
arr.reshape(1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 3)

array([[[[[[[[[[[[1., 1., 1.],
                 [1., 1., 1.]],

                [[1., 1., 1.],
                 [1., 1., 1.]]]]]]]]]]]])

In [208]:
lis = [1, 2, 3, 4]
arr = np.array(lis)

In [209]:
arr

array([1, 2, 3, 4])

In [210]:
arr.ndim

1

In [211]:
arr2 = np.array([[2, 3], [4, 5]])
arr2

array([[2, 3],
       [4, 5]])

In [212]:
arr2.ndim

2

In [213]:
arr2 = np.zeros((3, 4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [214]:
arr2.ndim

2

In [215]:
arr3 = np.zeros((1, 3, 4)) # 3 rows, 4 columns >> 2d array + 1d
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [216]:
arr3.ndim

3

In [217]:
arr4 = np.zeros((2,3, 4)) 
arr4

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [218]:
arr4.ndim

3

In [219]:
arr4.shape

(2, 3, 4)

In [220]:
arr1 = np.random.randint(1, 10, (5, 6))
arr1

array([[5, 4, 9, 3, 7, 9],
       [2, 7, 1, 5, 9, 2],
       [1, 5, 8, 8, 5, 6],
       [5, 7, 5, 1, 6, 9],
       [3, 8, 3, 1, 3, 4]])

In [229]:
arr1[[1,3],2:4]

array([[1, 5],
       [5, 1]])

In [231]:
arr1[2,1:3]

array([5, 8])

In [232]:
arr1[2][1:3]

array([5, 8])

In [233]:
arr1[2][1]

5

In [234]:
arr1[[1,3],2:4]

array([[1, 5],
       [5, 1]])

In [235]:
arr1[2,3]

8

In [236]:
arr1[2,[2,3]]

array([8, 8])

In [237]:
arr1[arr1 > 5]

array([9, 7, 9, 7, 9, 8, 8, 6, 7, 6, 9, 8])

In [238]:
arr1[arr1 == 5]

array([5, 5, 5, 5, 5, 5])

In [239]:
arr1[arr1 >= 8]

array([9, 9, 9, 8, 8, 9, 8])

In [240]:
arr1

array([[5, 4, 9, 3, 7, 9],
       [2, 7, 1, 5, 9, 2],
       [1, 5, 8, 8, 5, 6],
       [5, 7, 5, 1, 6, 9],
       [3, 8, 3, 1, 3, 4]])

In [241]:
# arr1[row,col]
arr1[1:4:2,2:4]

array([[1, 5],
       [5, 1]])

In [242]:
arr1[::2][1:4]

array([[1, 5, 8, 8, 5, 6],
       [3, 8, 3, 1, 3, 4]])

In [243]:
arr1[2,1]

5

In [244]:
arr1[2][2:4]

array([8, 8])

In [245]:
arr1[::2][1:4]

array([[1, 5, 8, 8, 5, 6],
       [3, 8, 3, 1, 3, 4]])

In [246]:
arr1[2,(2,3)]

array([8, 8])

In [247]:
arr1[[2],[2]]

array([8])

In [248]:
import numpy as np

In [249]:
arr1 = np.random.randint(1, 3, (3,3))
arr2 = np.random.randint(1, 3, (3,3))

In [253]:
arr1

array([[1, 2, 1],
       [2, 2, 2],
       [1, 2, 2]])

In [254]:
arr2

array([[1, 1, 1],
       [1, 2, 1],
       [2, 1, 2]])

In [255]:
arr1 + arr2

array([[2, 3, 2],
       [3, 4, 3],
       [3, 3, 4]])

In [257]:
arr1 - arr2

array([[ 0,  1,  0],
       [ 1,  0,  1],
       [-1,  1,  0]])

In [258]:
arr2 - arr1

array([[ 0, -1,  0],
       [-1,  0, -1],
       [ 1, -1,  0]])

In [259]:
arr1 * arr2

array([[1, 2, 1],
       [2, 4, 2],
       [2, 2, 4]])

In [269]:
arr1 = np.random.randint(1, 3, (5,3))
arr2 = np.random.randint(1, 3, (3,8))

In [270]:
#matrix multiplication


arr1

array([[1, 2, 2],
       [1, 1, 2],
       [1, 2, 1],
       [2, 1, 1],
       [2, 1, 2]])

In [271]:
arr2

array([[2, 2, 2, 1, 1, 2, 2, 2],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 2, 1, 2, 2]])

In [272]:
arr1 @ arr2

array([[ 6, 10,  6,  9,  7,  8,  8, 10],
       [ 5,  8,  5,  7,  6,  6,  7,  8],
       [ 5,  8,  5,  7,  5,  7,  6,  8],
       [ 6,  8,  6,  6,  5,  7,  7,  8],
       [ 7, 10,  7,  8,  7,  8,  9, 10]])

In [274]:
arr1.dot(arr2)

array([[ 6, 10,  6,  9,  7,  8,  8, 10],
       [ 5,  8,  5,  7,  6,  6,  7,  8],
       [ 5,  8,  5,  7,  5,  7,  6,  8],
       [ 6,  8,  6,  6,  5,  7,  7,  8],
       [ 7, 10,  7,  8,  7,  8,  9, 10]])

In [275]:
arr3 = np.random.randint(1, 3, (3,4))
arr4 = np.random.randint(1, 3, (4,4))

In [276]:
arr3

array([[2, 2, 1, 1],
       [2, 2, 2, 1],
       [1, 2, 2, 2]])

In [277]:
arr4

array([[2, 1, 1, 2],
       [1, 2, 1, 1],
       [1, 1, 1, 1],
       [1, 2, 2, 2]])

In [278]:
arr3 @ arr4

array([[ 8,  9,  7,  9],
       [ 9, 10,  8, 10],
       [ 8, 11,  9, 10]])

In [279]:
arr1

array([[1, 2, 2],
       [1, 1, 2],
       [1, 2, 1],
       [2, 1, 1],
       [2, 1, 2]])

In [280]:
arr2

array([[2, 2, 2, 1, 1, 2, 2, 2],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 2, 1, 2, 2]])

In [281]:
arr1 / 0

C:\Users\gaura\AppData\Local\Temp\ipykernel_11848\824215542.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [282]:
a = np.array([[1, 2, 3]])

In [283]:
a.shape

(1, 3)

In [284]:
a

array([[1, 2, 3]])

In [285]:
a.T

array([[1],
       [2],
       [3]])

In [286]:
a.T.shape

(3, 1)

In [288]:
arr = np.array([[1, 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [289]:
arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [290]:
arr.T

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [291]:
a

array([[1, 2, 3]])

In [292]:
arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [293]:
arr + a.T

array([[2., 2., 2., 2.],
       [4., 4., 4., 4.],
       [6., 6., 6., 6.]])

In [294]:
a = np.array([1, 2, 3])
a.T

array([1, 2, 3])

In [295]:
arr1

array([[1, 2, 2],
       [1, 1, 2],
       [1, 2, 1],
       [2, 1, 1],
       [2, 1, 2]])

In [298]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.41421356],
       [1.        , 1.        , 1.41421356],
       [1.        , 1.41421356, 1.        ],
       [1.41421356, 1.        , 1.        ],
       [1.41421356, 1.        , 1.41421356]])

In [299]:
np.square(arr1)

array([[1, 4, 4],
       [1, 1, 4],
       [1, 4, 1],
       [4, 1, 1],
       [4, 1, 4]], dtype=int32)

In [300]:
np.log10(arr1)

array([[0.     , 0.30103, 0.30103],
       [0.     , 0.     , 0.30103],
       [0.     , 0.30103, 0.     ],
       [0.30103, 0.     , 0.     ],
       [0.30103, 0.     , 0.30103]])

In [301]:
a

array([1, 2, 3])

In [302]:
np.min(a)

1

In [303]:
np.max(a)

3

In [304]:
np.mean(a)

2.0

In [305]:
np.median(a)

2.0

In [306]:
np.std(a)

0.816496580927726

In [307]:
np.var(a)

0.6666666666666666

In [309]:
np.min(arr1)

1

In [310]:
np.max(arr1)

2

In [311]:
arr1

array([[1, 2, 2],
       [1, 1, 2],
       [1, 2, 1],
       [2, 1, 1],
       [2, 1, 2]])

In [314]:
arr1.flatten()

array([1, 2, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2])

In [315]:
arr1.T

array([[1, 1, 1, 2, 2],
       [2, 1, 2, 1, 1],
       [2, 2, 1, 1, 2]])

In [316]:
a = np.array([[[[[1,2,3],[4,5,6]]]]])

In [317]:
a

array([[[[[1, 2, 3],
          [4, 5, 6]]]]])

In [318]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [319]:
arr1.flatten() #reduce higher dimension to 1 d

array([1, 2, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2])

In [320]:
arr1

array([[1, 2, 2],
       [1, 1, 2],
       [1, 2, 1],
       [2, 1, 1],
       [2, 1, 2]])

In [321]:
arr = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3]])

In [322]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [323]:
np.sum(arr)

27

In [324]:
np.sum(arr,axis = 1)

array([ 6, 15,  6])

In [325]:
np.sum(arr,axis = 0)

array([ 6,  9, 12])

In [326]:
#expand_dims >>expand the dimension of array
arr = np.array([[1, 2, 3, 4],[1, 2, 3, 4]])
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [327]:
arr.ndim

2

In [349]:
arr = np.expand_dims(arr, axis = 0)
arr

array([[[[[[[[[[[[[[[[[[[[[[[[1, 2, 3, 4],
                             [1, 2, 3, 4]]]]]]]]]]]]]]]]]]]]]]]])

In [350]:
arr.ndim

24

In [351]:
arr.flatten()

array([1, 2, 3, 4, 1, 2, 3, 4])

In [352]:
arr1

array([[1, 2, 2],
       [1, 1, 2],
       [1, 2, 1],
       [2, 1, 1],
       [2, 1, 2]])

In [353]:
arr2 = np.expand_dims(arr2, axis = 0)
arr2

array([[[2, 2, 2, 1, 1, 2, 2, 2],
        [1, 2, 1, 2, 1, 2, 1, 2],
        [1, 2, 1, 2, 2, 1, 2, 2]]])

In [354]:
arr2.shape

(1, 3, 8)

In [355]:
arr

array([[[[[[[[[[[[[[[[[[[[[[[[1, 2, 3, 4],
                             [1, 2, 3, 4]]]]]]]]]]]]]]]]]]]]]]]])

In [356]:
arr1 = np.expand_dims(arr, axis = 1)
arr1

array([[[[[[[[[[[[[[[[[[[[[[[[[1, 2, 3, 4],
                              [1, 2, 3, 4]]]]]]]]]]]]]]]]]]]]]]]]])

In [357]:
arr.flatten()

array([1, 2, 3, 4, 1, 2, 3, 4])

In [358]:
arr = np.zeros((3, 4))

In [359]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [360]:
arr1 = np.expand_dims(arr, axis = 1)
arr1

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [361]:
arr2 = np.expand_dims(arr1, axis = 0)
arr2

array([[[[0., 0., 0., 0.]],

        [[0., 0., 0., 0.]],

        [[0., 0., 0., 0.]]]])